// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCasparCGTemplates() {
  return window['go']['ui']['UIService']['GetCasparCGTemplates']();
}

export function GetDataSourceValue(arg1, arg2) {
  return window['go']['ui']['UIService']['GetDataSourceValue'](arg1, arg2);
}

export function GetDataSources() {
  return window['go']['ui']['UIService']['GetDataSources']();
}

export function LoadLayout() {
  return window['go']['ui']['UIService']['LoadLayout']();
}

export function PrimeDataSource(arg1, arg2) {
  return window['go']['ui']['UIService']['PrimeDataSource'](arg1, arg2);
}

export function PushCasparCGData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['ui']['UIService']['PushCasparCGData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PushCasparCGDataGroup(arg1) {
  return window['go']['ui']['UIService']['PushCasparCGDataGroup'](arg1);
}

export function SaveLayout(arg1) {
  return window['go']['ui']['UIService']['SaveLayout'](arg1);
}

export function StopCasparCGData(arg1, arg2, arg3, arg4) {
  return window['go']['ui']['UIService']['StopCasparCGData'](arg1, arg2, arg3, arg4);
}
