// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCasparCGTemplates() {
  return window['go']['ui']['UIService']['GetCasparCGTemplates']();
}

export function GetDataSources() {
  return window['go']['ui']['UIService']['GetDataSources']();
}

export function PushCasparCGData(arg1, arg2) {
  return window['go']['ui']['UIService']['PushCasparCGData'](arg1, arg2);
}
