// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {responses} from '../models';
import {ui} from '../models';
import {types} from '../models';

export function ClearAll():Promise<void>;

export function ClearChannels(arg1:string):Promise<void>;

export function Close():Promise<void>;

export function GetCasparCGMedia():Promise<Array<string>>;

export function GetCasparCGMediaInfo(arg1:string):Promise<responses.CINF>;

export function GetCasparCGTemplates():Promise<Array<string>>;

export function GetDataSources():Promise<Array<string>>;

export function LoadLayout():Promise<ui.LayoutConfig>;

export function NextCasparCGData(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function NextCasparCGDataGroup(arg1:Array<ui.CGDataGroup>):Promise<void>;

export function PlayCasparCGMedia(arg1:string,arg2:number,arg3:string,arg4:boolean,arg5:number):Promise<void>;

export function PlayCasparCGMediaGroup(arg1:Array<ui.MediaGroupItem>):Promise<void>;

export function PrimeDataSources(arg1:Array<types.FieldSubscription>):Promise<Array<types.FieldSubscriptionResult>>;

export function PushCasparCGData(arg1:string,arg2:number,arg3:string,arg4:Array<types.LiteralField>,arg5:types.Sizing,arg6:number):Promise<void>;

export function PushCasparCGDataGroup(arg1:Array<ui.CGDataGroup>):Promise<void>;

export function RemoveUpdateJob(arg1:string):Promise<void>;

export function SaveLayout(arg1:ui.LayoutConfig):Promise<void>;

export function StopCasparCGData(arg1:string,arg2:number,arg3:string,arg4:number):Promise<void>;

export function StopCasparCGDataGroup(arg1:Array<ui.CGDataGroup>):Promise<void>;

export function StopCasparCGMedia(arg1:number,arg2:string,arg3:number):Promise<void>;

export function StopCasparCGMediaGroup(arg1:Array<ui.MediaGroupItem>):Promise<void>;

export function UpdateCasparCGData(arg1:string,arg2:number,arg3:string,arg4:Array<types.LiteralField>,arg5:Array<ui.RangeField>,arg6:types.Sizing,arg7:number,arg8:number):Promise<string>;
