// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {ui} from '../models';
import {types} from '../models';
import {time} from '../models';

export function ClearAll():Promise<void>;

export function GetCasparCGTemplates():Promise<Array<string>>;

export function GetDataSourceValue(arg1:string,arg2:data.Location):Promise<data.Data>;

export function GetDataSources():Promise<Array<string>>;

export function LoadLayout():Promise<ui.LayoutConfig>;

export function PrimeDataSource(arg1:string,arg2:Array<data.Location>):Promise<void>;

export function PushCasparCGData(arg1:string,arg2:number,arg3:number,arg4:Record<string, any>,arg5:types.Sizing,arg6:time.Duration):Promise<void>;

export function PushCasparCGDataGroup(arg1:Array<ui.CGDataGroup>):Promise<void>;

export function SaveLayout(arg1:ui.LayoutConfig):Promise<void>;

export function StopCasparCGData(arg1:string,arg2:number,arg3:number,arg4:time.Duration):Promise<void>;

export function StopCasparCGDataGroup(arg1:Array<ui.CGDataGroup>):Promise<void>;
