// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCasparCGTemplates():Promise<Array<string>>;

export function GetDataSources():Promise<Array<string>>;

export function PushCasparCGData(arg1:string,arg2:Record<string, any>):Promise<void>;
