// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAll() {
  return window['go']['ui']['UIService']['ClearAll']();
}

export function ClearChannels(arg1) {
  return window['go']['ui']['UIService']['ClearChannels'](arg1);
}

export function Close() {
  return window['go']['ui']['UIService']['Close']();
}

export function GetCasparCGMedia() {
  return window['go']['ui']['UIService']['GetCasparCGMedia']();
}

export function GetCasparCGMediaInfo(arg1) {
  return window['go']['ui']['UIService']['GetCasparCGMediaInfo'](arg1);
}

export function GetCasparCGTemplates() {
  return window['go']['ui']['UIService']['GetCasparCGTemplates']();
}

export function GetDataSourceValue(arg1, arg2) {
  return window['go']['ui']['UIService']['GetDataSourceValue'](arg1, arg2);
}

export function GetDataSources() {
  return window['go']['ui']['UIService']['GetDataSources']();
}

export function LoadLayout() {
  return window['go']['ui']['UIService']['LoadLayout']();
}

export function NextCasparCGData(arg1, arg2, arg3, arg4) {
  return window['go']['ui']['UIService']['NextCasparCGData'](arg1, arg2, arg3, arg4);
}

export function PlayCasparCGMedia(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['ui']['UIService']['PlayCasparCGMedia'](arg1, arg2, arg3, arg4, arg5);
}

export function PrimeDataSource(arg1, arg2) {
  return window['go']['ui']['UIService']['PrimeDataSource'](arg1, arg2);
}

export function PushCasparCGData(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['ui']['UIService']['PushCasparCGData'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function PushCasparCGDataGroup(arg1) {
  return window['go']['ui']['UIService']['PushCasparCGDataGroup'](arg1);
}

export function RemoveUpdateJob(arg1) {
  return window['go']['ui']['UIService']['RemoveUpdateJob'](arg1);
}

export function SaveLayout(arg1) {
  return window['go']['ui']['UIService']['SaveLayout'](arg1);
}

export function StopCasparCGData(arg1, arg2, arg3, arg4) {
  return window['go']['ui']['UIService']['StopCasparCGData'](arg1, arg2, arg3, arg4);
}

export function StopCasparCGDataGroup(arg1) {
  return window['go']['ui']['UIService']['StopCasparCGDataGroup'](arg1);
}

export function StopCasparCGMedia(arg1, arg2, arg3) {
  return window['go']['ui']['UIService']['StopCasparCGMedia'](arg1, arg2, arg3);
}

export function UpdateCasparCGData(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['ui']['UIService']['UpdateCasparCGData'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}
