# Example YAML config for this application
# This is not run ready and simply shows all possibilities that can be configured in the config

data_source_manager:
  google_sheet_data_sources:
    - spreadsheet_id: "your_spreadsheet_id"
      credentials_file_path: "path/to/your/credentials.json"
    - spreadsheet_id: "another_spreadsheet_id"
      credentials_file_path: "path/to/another/credentials.json"
